=== MiguelCastanedaDev/portfolio/.astro/collections/products.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "image": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "image",
    "title",
    "description",
    "link"
  ]
}

=== MiguelCastanedaDev/portfolio/src/content/products/lume.json
{
    "image": "/images/lume.png",
    "title": "Lumé Studio",
    "description": "Sitio web estático diseñado para un negocio de uñas, enfocado en presentar de forma clara y atractiva los servicios, precios y estilos disponibles, facilitando la captación de clientes y el contacto directo sin necesidad de funcionalidades dinámicas complejas.",
    "link": "https://lume-studio.mikeonlinemx.workers.dev/"
}

=== MiguelCastanedaDev/portfolio/src/content/products/billpoint.json
{
    "image": "/images/billpoint.png",
    "title": "Billpoint v1.0.4",
    "description": "Billpoint es una aplicación de facturación mexicana CFDI 4.0 y gestión de clientes diseñada para pequeñas/medianas empresas. Permite crear y enviar facturas personalizadas, gestionar clientes y productos, y realizar un seguimiento de los pagos de manera eficiente.",
    "link": "https://client-billing-pos.mikeonlinemx.workers.dev/"
}

=== MiguelCastanedaDev/portfolio/src/content/products/smart-key.json
{
    "image": "/images/smart-key.png",
    "title": "Smart Key",
    "description": "Smart Key es una Plataforma tecnológica para mejorar la comunicación escrita entre personas y sistemas digitales, mejorando la interacción con inteligencia artificial mediante prompts más precisos.",
    "link": "https://smart-key.mx/"
}
